<?php

namespace PlayList\PlayBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayRepository extends EntityRepository
{
}
